name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: sudo apt-get install libwebkit2gtk-4.1-dev libgtk-3-dev libayatana-appindicator3-dev
      - name: Build
        run: cargo build --verbose
      - name: Run clippy
        run: cargo clippy --verbose
      - name: Run tests
        run: cargo test --verbose

  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: "Dioxus Deploy"
        uses: davidMcneil/dioxus-deploy-action@c0c390be1298b58e8b47850cf1e85c3fcf13772c
        with:
          buildMode: "release"
          features: "web"
          toolchain: "stable"
          outDirectory: "dist"
